name: Test

on:
  push:
  pull_request:
  schedule:
    # Weekly, at 5:45 AM on Friday (somewhat randomly chosen).
    - cron: '45 5 * * 5'
  workflow_dispatch:

jobs:
  sign_pss_windows:
    runs-on: windows-latest
    name: 'test sign-pss windows'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Sign Example PSM Game
        uses: ./
        with:
            input: test/PsmTestSuite
            output: test/PsmTestSuite-signed
            content_id: UM0999-NPNA99999_00-0000000000000000
  sign_pss_linux:
    runs-on: ubuntu-latest
    name: 'test sign-pss linux'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Sign Example PSM Game
        uses: ./
        with:
            input: test/PsmTestSuite
            output: test/PsmTestSuite-signed
            content_id: UM0999-NPNA99999_00-0000000000000000
  sign_pss_macos:
    runs-on: macos-latest
    name: 'test sign-pss macos'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Sign Example PSM Game
        uses: ./
        with:
            input: test/PsmTestSuite
            output: test/PsmTestSuite-signed
            content_id: UM0999-NPNA99999_00-0000000000000000